#!/bin/env python3

"""
This script displays the Gregorian equivalent of a given Cyprian date.
"""

# Standard imports.
import argparse
from sys import exit

# Bespoke imports.
from cyprian_datetime import CyprianDateTime

####################
# HELPER FUNCTIONS #
####################

def make_parser() -> argparse.ArgumentParser:
    """ Make the object which handles the command-line interface. """
    result = argparse.ArgumentParser()
    result.add_argument(
        "date_str",
        help="The Cyprian date to be converted, in DD-MMM-TY format"
    )
    return result

def convert_date_str(date_str: str|None) -> CyprianDateTime|None:
    """
    Get the CyprianDateTime object corresponding to a Gregorian date, with both
    input and output being given in string form.
    """
    try:
        result = CyprianDateTime.from_cyprian_str(date_str)
    except:
        print(f"Something's not quite right with that date string: {date_str}")
        print("Is it in DD-MMM-TY format?")
        return None
    return result

###################
# RUN AND WRAP UP #
###################

def run():
    """ Run this script. """
    parser_obj = make_parser()
    args_obj = parser_obj.parse_args()
    date_str = args_obj.date_str
    converted = convert_date_str(date_str)
    if converted:
        print(converted)
    else:
        exit(1)

if __name__ == "__main__":
    run()
